# -*- coding: utf-8 -*-
"""
REV20 — Edebî Terimler/Kavramlar Taksonomisi

Her dönemin kendine özgü terim/tür/kavramları (fütüvvetname, sefaretname, sagu,
koşuk, gazel, tezkire...) tek çatıda. İki çıktı:
  1. data/terimler_kaynak.json        → generate_data.gen_terim_cards() kart üretir
  2. public/data/edebiyat/terimler.json → /terimler sayfası (sözlük) gösterir

Tanımlar MEBİ özet + ÖSYM kanonundan; SPOILER-FREE (tanım, terimin adını içermez →
'tanım → terim' sorusu çözülebilir kalır).

Aşamalı: REV20a = divan_nesir + isl_oncesi. REV20b/c diğer kategorileri ekler.
"""
import json
import sys
import io
import re
import unicodedata
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

ROOT = Path(__file__).resolve().parent.parent.parent          # Edebiyat Analiz/
SITE = ROOT / 'edebiyat-site' / 'public' / 'data' / 'edebiyat'
OUT_KAYNAK = ROOT / 'data' / 'terimler_kaynak.json'
OUT_PAGE = SITE / 'terimler.json'

# Kategori → (etiket, topic-konu kodu, dönem etiketi, sıra)
KATEGORI = {
    'isl_oncesi':         ('İslamiyet Öncesi Türleri',   'islamiyet_oncesi_gecis', 'İslamiyet Öncesi / Sözlü Dönem', 10),
    # Halk Edebiyatı
    'halk_anonim':        ('Anonim Halk Şiiri',          'halk_edebiyati',         'Halk Edebiyatı', 20),
    'halk_asik_bicim':    ('Âşık Edebiyatı Nazım Biçimleri', 'halk_edebiyati',     'Halk Edebiyatı', 21),
    'halk_asik_tur':      ('Âşık Edebiyatı Nazım Türleri (Koşma Konuları)', 'halk_edebiyati', 'Halk Edebiyatı', 22),
    'halk_tekke':         ('Tekke / Tasavvuf Nazım Türleri', 'halk_edebiyati',     'Halk Edebiyatı', 23),
    'halk_nesir':         ('Halk Nesri / Anonim Türler',  'masal_fabl_destan',     'Halk Edebiyatı', 24),
    'halk_seyirlik':      ('Geleneksel Türk Tiyatrosu',   'geleneksel_tiyatro',    'Halk Edebiyatı', 25),
    'tasavvuf_kavram':    ('Tasavvuf Kavramları',         'halk_edebiyati',        'Halk Edebiyatı', 26),
    # Divan Edebiyatı
    'divan_nazim_bicim':  ('Divan Nazım Biçimleri',       'divan_edebiyati',       'Divan Edebiyatı', 41),
    'divan_nazim_tur':    ('Divan Nazım Türleri (Konuya Göre)', 'divan_edebiyati',  'Divan Edebiyatı', 42),
    'divan_gazel_terim':  ('Gazel/Kaside Terimleri',      'divan_edebiyati',       'Divan Edebiyatı', 43),
    'divan_uslup':        ('Divan Üslupları',             'divan_edebiyati',       'Divan Edebiyatı', 44),
    'divan_nesir':        ('Divan Nesir Türleri',         'nesir_bilgisi',          'Divan Edebiyatı', 45),
    # Tanzimat / Servet-i Fünun / Milli / Cumhuriyet kavramları
    'tanzimat_kavram':    ('Tanzimat Kavramları',         'tanzimat',               'Tanzimat', 50),
    'sf_kavram':          ('Servet-i Fünun / Fecr-i Âti Kavramları', 'servet_i_funun_fecr_i_ati', 'Servet-i Fünun / Fecr-i Âti', 55),
    'milli_kavram':       ('Milli Edebiyat Kavramları',   'milli_edebiyat',         'Milli Edebiyat', 60),
    'cumhuriyet_topluluk':('Cumhuriyet Şiir Toplulukları','cumhuriyet',             'Cumhuriyet', 70),
    'cumhuriyet_kavram':  ('Roman / Anlatım Kavramları',  'cumhuriyet',             'Cumhuriyet', 71),
    # Genel
    'siir_birim':         ('Nazım Birimi · Ölçü · Kafiye','siir_bilgisi',           'Genel / Şiir Bilgisi', 80),
    'siir_turu':          ('Şiir Türleri',                'siir_bilgisi',           'Genel / Şiir Bilgisi', 81),
    'nesir_tur':          ('Düzyazı (Nesir) Türleri',     'nesir_bilgisi',          'Genel / Nesir Türleri', 84),
    'soz_sanati':         ('Söz (Edebî) Sanatları',       'soz_sanatlari',          'Söz Sanatları', 82),
    'akim':               ('Batı Edebiyatı Akımları',     'edebi_akimlar',          'Batı Edebiyatı Akımları', 90),
}
DONEM_SIRA = {
    'İslamiyet Öncesi / Sözlü Dönem': 10,
    'Geçiş Dönemi': 15,
    'Halk Edebiyatı': 20,
    'Divan Edebiyatı': 40,
    'Tanzimat': 50,
    'Servet-i Fünun / Fecr-i Âti': 55,
    'Milli Edebiyat': 60,
    'Cumhuriyet': 70,
    'Genel / Şiir Bilgisi': 80,
    'Söz Sanatları': 82,
    'Genel / Nesir Türleri': 84,
    'Batı Edebiyatı Akımları': 90,
}

# =====================================================================
# TERİMLER — (terim, kategori, tanim, ornek, ayirt_edici, ozellikler[])
#   tanim: terim adını GEÇİRMEZ (spoiler-free)
#   ozellikler: terim→özellik + negatif eleme için doğru özellikler
# =====================================================================
TERIMLER = [
    # ============ İSLAMİYET ÖNCESİ / SÖZLÜ DÖNEM ============
    ("Koşuk", "isl_oncesi",
     "Sığır ve şölen gibi törenlerde kopuz eşliğinde söylenen; aşk, doğa, yiğitlik konularını işleyen lirik şiir.",
     "Halk edebiyatındaki koşmanın atası sayılır.",
     "Sagu ÖLÜM/yas içindir; bu tür aşk-doğa-coşku içindir.",
     ["lirik", "kopuz eşliğinde", "aşk-doğa-yiğitlik", "sığır/şölen töreni"]),
    ("Sagu", "isl_oncesi",
     "Ölen bir kişinin ardından yuğ töreninde söylenen, yas ve övgü içeren ağıt niteliğindeki şiir.",
     "Alp Er Tunga Sagusu.",
     "Halk edebiyatında 'ağıt', Divan'da 'mersiye' karşılığıdır.",
     ["ağıt", "yuğ töreni", "ölüm/yas teması", "övgü"]),
    ("Sav", "isl_oncesi",
     "Geçmiş deneyimlerden doğan, kısa ve özlü söz; günümüz atasözünün karşılığı.",
     "Divânü Lugâti't-Türk'te birçok örneği geçer.",
     "Atasözünün İslamiyet öncesi adıdır; bir şiir türü değil özlü sözdür.",
     ["özlü söz", "atasözü karşılığı", "didaktik", "kısa"]),
    ("Destan (Sözlü Dönem)", "isl_oncesi",
     "Bir milletin hafızasında yer etmiş olağanüstü olayları, kahramanlıkları anlatan uzun manzum anlatı.",
     "Oğuz Kağan, Bozkurt, Ergenekon.",
     "Yapma destandan farkı: anonim ve sözlü gelenekten doğmasıdır.",
     ["uzun manzum", "kahramanlık", "olağanüstü öğeler", "anonim"]),
    ("Sığır", "isl_oncesi",
     "İslamiyet öncesi Türklerde yapılan sürek avı niteliğindeki tören; bu törenlerde şiirler söylenirdi.",
     "",
     "Şölen ziyafet/kurban töreni; bu ise AV törenidir.",
     ["sürek avı töreni", "şiir söylenir", "dini-toplumsal"]),
    ("Şölen (Toy)", "isl_oncesi",
     "İslamiyet öncesi Türklerde kurban sunulan dini ziyafet ve toplanma töreni.",
     "",
     "Yuğ yas, sığır av; bu ise ziyafet/kurban törenidir.",
     ["dini ziyafet", "kurban", "toplanma", "toy"]),
    ("Yuğ", "isl_oncesi",
     "Ölen kişinin ardından düzenlenen yas ve cenaze töreni; bu törende sagular söylenirdi.",
     "",
     "Sığır av, şölen ziyafet; bu ise YAS törenidir, sagu burada söylenir.",
     ["yas/cenaze töreni", "sagu söylenir", "ölüm"]),
    ("Ozan", "isl_oncesi",
     "Kopuz eşliğinde şiir söyleyen, destan anlatan sözlü dönem sanatçısı; halk edebiyatında 'âşık'ın karşılığı.",
     "",
     "Kam/baksı şair+hekim+büyücü; ozan ise daha çok şiir/destan söyleyendir.",
     ["şiir/destan söyler", "kopuz", "âşığın atası", "sözlü gelenek"]),
    ("Kam (Baksı / Şaman)", "isl_oncesi",
     "İslamiyet öncesi Türklerde hem şair hem hekim hem büyücü olan; dini törenleri yöneten sanatçı-din adamı.",
     "",
     "Ozan sadece şiir/destan söyler; bu kişi ayrıca hekimlik+büyü+din görevi taşır.",
     ["şair-hekim-büyücü", "dini tören yöneticisi", "çok işlevli"]),

    # ============ HALK — ANONİM ŞİİR ============
    ("Mâni", "halk_anonim",
     "Çoğunlukla yedi heceli, dört dizeli (aaxa); ilk iki dizesi doldurma olan, asıl anlamın son iki dizede verildiği anonim ürün.",
     "Düz, kesik (cinaslı), yedekli türleri vardır.",
     "Koşma on bir heceli ve âşık ürünüdür; bu yedi heceli ve anonimdir.",
     ["anonim", "yedi heceli", "aaxa uyak", "dört dize", "ilk iki dize doldurma"]),
    ("Türkü", "halk_anonim",
     "Bir ezgiyle söylenen; bentlerden ve her bendin sonunda yinelenen kavuştaktan (nakarat) oluşan anonim ürün.",
     "",
     "Mâni tek dörtlüktür; bu bent + kavuştak yapısındadır.",
     ["ezgiyle söylenir", "kavuştak/nakarat", "bent yapısı", "anonim"]),
    ("Ninni", "halk_anonim",
     "Çocuğu uyutmak amacıyla ezgiyle söylenen; annenin duygularını yansıtan anonim ürün.",
     "",
     "Ağıt ölüm acısı içindir; bu uyutma/sevgi amaçlıdır.",
     ["çocuğu uyutmak", "ezgili", "anne duygusu", "anonim"]),
    ("Ağıt (Anonim)", "halk_anonim",
     "Ölüm, hastalık, doğal afet gibi acı olaylar karşısında duyulan üzüntüyü dile getiren anonim söyleyiş.",
     "",
     "İslamiyet öncesi karşılığı sagu, Divan'da mersiyedir.",
     ["ölüm/acı teması", "üzüntü", "anonim", "yas"]),
    ("Bilmece", "halk_anonim",
     "Bir nesne ya da kavramı kapalı biçimde tanımlayıp buldurmayı amaçlayan, kalıplaşmış anonim söz.",
     "",
     "Tekerleme ses oyunudur; bu buldurma amaçlıdır.",
     ["buldurma amaçlı", "kapalı tanım", "kalıplaşmış", "anonim"]),
    ("Tekerleme", "halk_anonim",
     "Ses ve sözcük benzerliğine dayanan, çoğu zaman mantık dışı, oyun ve masal başlarında söylenen ritmik söz.",
     "Masal döşemesi (bir varmış bir yokmuş...).",
     "Bilmece buldurur; bu ritim/ses oyunu içindir.",
     ["ses oyunu", "mantık dışı", "ritmik", "masal döşemesi"]),

    # ============ HALK — ÂŞIK NAZIM BİÇİMLERİ ============
    ("Koşma", "halk_asik_bicim",
     "On birli hece ölçüsüyle, dört dizeli bentlerden oluşan; aşk, doğa ve özlem konularını işleyen âşık şiiri biçimi.",
     "Karacaoğlan'ın koşmaları.",
     "Mâni yedi heceli ve anonimdir; bu on bir heceli ve âşık ürünüdür.",
     ["on bir hece", "dörtlük bentler", "âşık ürünü", "aşk-doğa", "son dörtlükte mahlas"]),
    ("Semai (Âşık)", "halk_asik_bicim",
     "Sekizli hece ölçüsüyle, kendine özgü bir ezgiyle söylenen; koşmaya benzeyen lirik âşık şiiri biçimi.",
     "",
     "Koşma on bir, bu sekiz hecelidir; varsağıdan farkı yiğitçe eda taşımamasıdır.",
     ["sekiz hece", "özel ezgi", "âşık ürünü", "lirik"]),
    ("Varsağı", "halk_asik_bicim",
     "Sekizli hece ölçüsüyle, yiğitçe ve mertçe bir edayla; 'bre, behey' gibi seslenişlerle söylenen âşık şiiri biçimi.",
     "Dadaloğlu, Karacaoğlan.",
     "Semai lirik/yumuşak; bu yiğitçe/mertçe edalıdır.",
     ["sekiz hece", "yiğitçe eda", "bre/behey nidası", "âşık ürünü"]),
    ("Destan (Âşık)", "halk_asik_bicim",
     "Aşıkların savaş, kahramanlık, salgın ya da mizah gibi konuları uzun uzun anlattığı; en uzun âşık şiiri biçimi.",
     "",
     "Koşma kısadır; bu en uzun biçimdir ve olay anlatır.",
     ["en uzun biçim", "olay anlatımı", "dörtlük", "çok konulu"]),

    # ============ HALK — ÂŞIK NAZIM TÜRLERİ (KOŞMA KONULARI) ============
    ("Güzelleme", "halk_asik_tur",
     "Bir kişiyi, doğayı ya da sevgiliyi övmek; güzelliği yüceltmek amacıyla söylenen koşma konusu.",
     "Karacaoğlan.",
     "Koçaklama kahramanlık; bu güzellik/övgü içindir.",
     ["övgü", "sevgili-doğa güzelliği", "lirik", "Karacaoğlan"]),
    ("Koçaklama", "halk_asik_tur",
     "Savaş, kahramanlık ve yiğitlik konularını coşkulu bir dille işleyen koşma konusu.",
     "Köroğlu, Dadaloğlu.",
     "Güzelleme aşk/övgü; bu kahramanlık/coşkudur.",
     ["kahramanlık", "yiğitlik", "coşku", "Köroğlu-Dadaloğlu"]),
    ("Taşlama", "halk_asik_tur",
     "Bir kişiyi ya da toplumsal düzeni eleştirmek, yermek amacıyla söylenen koşma konusu.",
     "Seyrani.",
     "Divan'daki hicviyenin karşılığıdır.",
     ["yergi/eleştiri", "toplumsal", "Seyrani"]),

    # ============ HALK — TEKKE / TASAVVUF NAZIM TÜRLERİ ============
    ("İlahi", "halk_tekke",
     "Allah aşkını, dini ve tasavvufi düşünceyi; tarikat ayrımı gözetmeden ezgiyle dile getiren tekke şiiri.",
     "Yunus Emre.",
     "Nefes Bektaşilere özgüdür; bu tarikat ayrımı gözetmez.",
     ["Allah aşkı", "ezgili", "tasavvuf", "Yunus Emre"]),
    ("Nefes", "halk_tekke",
     "Bektaşi şairlerinin söylediği; varlık birliğini ve tasavvufi neşeyi kimi zaman iğneli bir dille işleyen tekke şiiri.",
     "Pir Sultan Abdal.",
     "İlahi genel tasavvuf; bu özellikle Bektaşi geleneğindendir.",
     ["Bektaşi", "varlık birliği", "kimi zaman iğneli", "Pir Sultan"]),
    ("Nutuk", "halk_tekke",
     "Tarikata yeni girenlere yol ve âdâbı öğretmek için söylenen öğretici tekke şiiri.",
     "",
     "Devriye 'devir' felsefesini anlatır; bu öğüt/öğreti içindir.",
     ["öğretici", "tarikat âdâbı", "didaktik", "yeni dervişlere"]),
    ("Devriye", "halk_tekke",
     "Varlığın Hak'tan çıkıp tekrar Hakk'a dönüşü (devir) inancını anlatan tekke şiiri.",
     "",
     "Nutuk öğüt verir; bu 'devir' felsefesini işler.",
     ["devir felsefesi", "Hak'tan çıkış-dönüş", "tasavvufi", "felsefi"]),
    ("Şathiye", "halk_tekke",
     "Dini konuları, ilk bakışta aykırı/saçma görünen ama derinde tasavvufi anlam taşıyan iğneli ve mizahi bir dille işleyen tekke şiiri.",
     "Kaygusuz Abdal.",
     "İlahi ciddi/lirik; bu mizahi ve görünüşte aykırıdır.",
     ["mizahi/iğneli", "görünüşte aykırı", "derinde tasavvuf", "Kaygusuz Abdal"]),

    # ============ HALK NESRİ / ANONİM TÜRLER ============
    ("Halk Hikâyesi", "halk_nesir",
     "Genellikle aşk ya da kahramanlık konulu; nazım-nesir karışık, âşıklarca anlatılan, destandan romana geçiş sayılan tür.",
     "Kerem ile Aslı, Köroğlu.",
     "Destan tümüyle manzumdur; bu nazım-nesir karışıktır.",
     ["nazım-nesir karışık", "aşk/kahramanlık", "âşık anlatır", "destan-roman geçişi"]),
    ("Masal", "halk_nesir",
     "Olağanüstü olay ve kişilerin yer aldığı; belirli bir zaman-mekâna bağlı olmayan, tekerlemeli anonim anlatı.",
     "",
     "Efsane gerçeklik iddialıdır; bu tümüyle hayalîdir.",
     ["olağanüstü", "hayalî", "tekerleme/döşeme", "anonim", "ders verir"]),
    ("Efsane", "halk_nesir",
     "Bir varlığın, yerin ya da olayın oluşumunu; inanış ögesiyle ve gerçek olduğu iddiasıyla açıklayan anlatı.",
     "",
     "Masal hayalîdir; bu gerçeklik iddiası taşır. Menkıbe veli kerameti içindir.",
     ["oluşum açıklar", "gerçeklik iddiası", "inanış ögesi", "olağanüstü"]),
    ("Menkıbe", "halk_nesir",
     "Bir din büyüğünün ya da velinin kerametlerini anlatan, inanca dayalı anlatı.",
     "",
     "Efsane genel oluşum; bu veli kerameti anlatır.",
     ["veli kerameti", "din büyüğü", "inanç", "olağanüstü hâl"]),
    ("Fıkra (Halk)", "halk_nesir",
     "Toplumsal bir gerçeği güldürü ve nükteyle, kısa bir olay çevresinde anlatan anonim/sözlü tür.",
     "Nasreddin Hoca, Bektaşi fıkraları.",
     "Gazete fıkrası yazılı ve imzalıdır; bu sözlü ve anonimdir.",
     ["güldürü/nükte", "kısa olay", "sözlü-anonim", "ders verir"]),

    # ============ GELENEKSEL TÜRK TİYATROSU ============
    ("Karagöz", "halk_seyirlik",
     "Deriden yapılmış tasvirlerin perde arkasından ışıkla yansıtıldığı gölge oyunu; giriş-muhavere-fasıl-bitiş bölümlerinden oluşur.",
     "",
     "Orta oyununda canlı oyuncu vardır; bu gölge/tasvir oyunudur.",
     ["gölge oyunu", "tasvir/perde", "dört bölüm", "Hacivat-Karagöz"]),
    ("Orta Oyunu", "halk_seyirlik",
     "Çevresi seyircilerle çevrili açık alanda (palanga), canlı oyuncularla doğaçlama oynanan geleneksel oyun.",
     "",
     "Karagöz gölge oyunudur; bu canlı oyuncularla oynanır.",
     ["açık alan/palanga", "canlı oyuncu", "doğaçlama", "Pişekâr-Kavuklu"]),
    ("Meddah", "halk_seyirlik",
     "Tek kişilik anlatıcının; mendil ve sopa kullanarak taklitlerle bir hikâye anlattığı seyirlik tür.",
     "",
     "Karagöz/orta oyunu çok kişilik; bu tek kişiliktir.",
     ["tek kişilik", "mendil-sopa", "taklit", "kahvehane"]),
    ("Köy Seyirlik Oyunu", "halk_seyirlik",
     "Tarım toplumunda düğün, bayram ve mevsim geçişlerinde; bolluk-bereket dileğiyle amatörce oynanan törensel/ritüel oyunlar.",
     "",
     "Karagöz/meddah profesyonelce şehirde oynanır; bu kırsalda amatör ve ritüeldir.",
     ["amatör oyuncu", "mevsim ritüeli", "bolluk-bereket dileği", "törensel"]),

    # ============ TASAVVUF KAVRAMLARI ============
    ("Vahdet-i Vücud", "tasavvuf_kavram",
     "Varlığın tek olduğu; var olan her şeyin Hakk'ın bir görünümü/yansıması sayıldığı tasavvuf anlayışı.",
     "İbnü'l-Arabî.",
     "Fenafillah bireyin yok oluşu hâlidir; bu bir varlık öğretisidir.",
     ["varlık birliği", "her şey Hakk'ın yansıması", "İbnü'l-Arabî", "öğreti"]),
    ("Fenafillah", "tasavvuf_kavram",
     "Kişinin kendi benliğinden geçip varlığını Allah'ta yok etmesi/eritmesi hâli.",
     "",
     "Vahdet-i vücud bir öğretidir; bu bireysel bir manevi hâldir.",
     ["benlikten geçiş", "Allah'ta yok oluş", "manevi hâl", "tasavvuf hedefi"]),
    ("Tecelli", "tasavvuf_kavram",
     "İlahi varlığın evrendeki nesne ve olaylarda görünür/belirir hâle gelmesi.",
     "",
     "Fenafillah yok oluş; bu görünür olma/belirmedir.",
     ["ilahi görünüm", "belirme", "vahdet-i vücud ile ilişkili"]),
    ("İnsan-ı Kâmil", "tasavvuf_kavram",
     "Tasavvufta olgunluğun zirvesine ulaşmış; Hakk'ı kendinde yansıtan ideal, olgun insan.",
     "",
     "Bir kavram/insandır, hâl değildir.",
     ["olgun insan", "manevi zirve", "Hakk'ı yansıtır"]),

    # ============ DİVAN NAZIM BİÇİMLERİ ============
    ("Gazel", "divan_nazim_bicim",
     "Beyitlerle yazılan; ilk beyti kendi arasında, sonraki beyitleri 'aa-ba-ca' düzeninde uyaklı; çoğunlukla aşk-şarap-güzellik konulu biçim.",
     "",
     "Kaside uzun ve övgü amaçlıdır; bu kısa ve aşk konuludur.",
     ["beyit", "aa-ba-ca uyak", "beş-on beş beyit", "aşk-şarap", "matla-makta"]),
    ("Kaside", "divan_nazim_bicim",
     "Genellikle bir büyüğü övmek için yazılan; gazelle aynı uyak düzeninde ama daha uzun (otuz üç-doksan dokuz beyit) biçim.",
     "",
     "Gazel kısa ve aşk konuludur; bu uzun ve övgü amaçlıdır.",
     ["övgü/methiye", "uzun (33-99 beyit)", "aa-ba-ca uyak", "nesib-girizgâh-methiye bölümleri"]),
    ("Mesnevi", "divan_nazim_bicim",
     "Her beyti kendi içinde uyaklı (aa-bb-cc) olan; uzun aşk, kahramanlık ya da öğretici konuların işlendiği biçim.",
     "Leyla vü Mecnun, Hüsn ü Aşk.",
     "Gazel/kasidede tek uyak sürer; bu her beyitte ayrı uyaktır.",
     ["aa-bb-cc uyak", "uzun konu", "hikâye/öğreti", "her beyit ayrı uyak"]),
    ("Rubai", "divan_nazim_bicim",
     "Tek dörtlükten oluşan; kendine özgü aruz kalıplarıyla yazılan, felsefi-tasavvufi düşünceyi yoğun anlatan biçim.",
     "Mevlana, Ömer Hayyam.",
     "Tuyuğ Türklere özgü ve cinaslıdır; bu İran kökenlidir.",
     ["tek dörtlük", "aaxa", "felsefi düşünce", "İran kökenli"]),
    ("Tuyuğ", "divan_nazim_bicim",
     "Türklerin Divan edebiyatına kazandırdığı; tek dörtlükten oluşan, cinaslı uyak kullanılan, mâni etkili biçim.",
     "Kadı Burhanettin, Nesimî.",
     "Rubai İran kökenlidir; bu Türklere özgü ve cinaslıdır.",
     ["Türklere özgü", "tek dörtlük", "cinaslı uyak", "mâni etkili"]),
    ("Şarkı", "divan_nazim_bicim",
     "Bestelenmek üzere yazılan; dörtlük bentli, nakaratlı (her bendin belli dizesi yinelenen) biçim.",
     "Nedim.",
     "Murabba bestelenmek için değildir; bu bestelenir ve nakaratlıdır.",
     ["bestelenir", "nakarat", "dörtlük bent", "Nedim"]),
    ("Müstezat", "divan_nazim_bicim",
     "Bir gazelin her dizesine kısa bir dize (ziyade) eklenerek oluşturulan biçim.",
     "",
     "Gazelden farkı her dizeye eklenen kısa ziyade dizelerdir.",
     ["gazel + ziyade dize", "uzun-kısa dize", "Divan biçimi"]),
    ("Terkib-i Bend", "divan_nazim_bicim",
     "Bentlerden oluşan; her bendin sonunda farklı bir vasıta beyti bulunan; çoğunlukla mersiye/toplumsal eleştiri konulu biçim.",
     "Bağdatlı Ruhi, Ziya Paşa.",
     "Terci-i bendde vasıta beyti aynıdır; burada her bentte farklıdır.",
     ["bentler", "farklı vasıta beyti", "mersiye/eleştiri"]),
    ("Terci-i Bend", "divan_nazim_bicim",
     "Bentlerden oluşan; her bendin sonunda aynı vasıta beyti yinelenen biçim.",
     "Ziya Paşa.",
     "Terkib-i bendde vasıta beyti değişir; burada aynı beyit tekrarlanır.",
     ["bentler", "aynı vasıta beyti tekrar", "Divan biçimi"]),

    # ============ DİVAN NAZIM TÜRLERİ (KONUYA GÖRE) ============
    ("Tevhid", "divan_nazim_tur",
     "Allah'ın birliğini ve yüceliğini anlatan Divan şiiri konusu.",
     "",
     "Münacat yakarış/duadır; bu Allah'ın birliğini anlatır.",
     ["Allah'ın birliği", "dini", "yüceltme"]),
    ("Münacat", "divan_nazim_tur",
     "Allah'a yakarış, dua ve yalvarışı içeren Divan şiiri konusu.",
     "",
     "Tevhid birliği anlatır; bu yakarış/duadır.",
     ["Allah'a yakarış", "dua", "dini"]),
    ("Naat", "divan_nazim_tur",
     "Hz. Muhammed'i övmek için yazılan Divan şiiri konusu.",
     "Fuzuli, Su Kasidesi.",
     "Methiye devlet büyüğünü över; bu peygamberi över.",
     ["Hz. Muhammed övgüsü", "dini", "Su Kasidesi"]),
    ("Methiye", "divan_nazim_tur",
     "Bir devlet büyüğünü ya da ileri geleni övmek için yazılan; kasidenin de bir bölümü olan tür.",
     "",
     "Naat peygamberi över; bu devlet büyüğünü över.",
     ["devlet büyüğü övgüsü", "kasidede bölüm", "övgü"]),
    ("Mersiye", "divan_nazim_tur",
     "Bir kişinin ölümünden duyulan üzüntüyü anlatan; ölenin meziyetlerini öven tür.",
     "Baki, Kanuni Mersiyesi.",
     "Halk şiirinde ağıt, İslam öncesinde sagu karşılığıdır.",
     ["ölüm/yas", "övgü", "Baki Kanuni Mersiyesi"]),
    ("Hicviye", "divan_nazim_tur",
     "Bir kişiyi ya da durumu yermek, eleştirmek amacıyla yazılan tür.",
     "Nef'i, Siham-ı Kaza.",
     "Halk şiirindeki taşlamanın karşılığıdır.",
     ["yergi/eleştiri", "Nef'i Siham-ı Kaza", "alay"]),
    ("Fahriye", "divan_nazim_tur",
     "Şairin kendini ve sanatını övdüğü bölüm/tür.",
     "",
     "Methiye başkasını över; bu şairin kendini övmesidir.",
     ["şairin kendini övmesi", "kasidede bölüm", "övünme"]),

    # ============ GAZEL / KASİDE TERİMLERİ ============
    ("Matla", "divan_gazel_terim",
     "Gazel ya da kasidenin, iki dizesi de birbiriyle uyaklı olan ilk beyti.",
     "",
     "Makta son beyittir; bu ilk beyittir.",
     ["ilk beyit", "iki dize uyaklı", "gazel başı"]),
    ("Makta", "divan_gazel_terim",
     "Gazelin, şairin takma adının (mahlas) geçtiği son beyti.",
     "",
     "Matla ilk beyittir; bu son beyittir, şair adı burada geçer.",
     ["son beyit", "mahlas burada", "gazel sonu"]),
    ("Mahlas", "divan_gazel_terim",
     "Divan şairinin şiirlerinde kullandığı takma ad; çoğunlukla son beyitte geçer.",
     "",
     "Bir beyit değil, şairin takma adıdır.",
     ["takma ad", "son beyitte", "tac beyit"]),
    ("Beytü'l-gazel (Şah Beyit)", "divan_gazel_terim",
     "Bir gazelin en güzel, en başarılı sayılan beyti.",
     "",
     "Yeri sabit değildir; en güzel beyittir.",
     ["en güzel beyit", "şah beyit"]),

    # ============ DİVAN ÜSLUPLARI ============
    ("Sebk-i Hindi", "divan_uslup",
     "On yedinci yüzyılda yaygınlaşan; derin hayaller, ince/karmaşık mazmunlar ve kapalı söyleyişe dayanan üslup.",
     "Naili, Şeyh Galip.",
     "Mahallileşme yerlilik/sadelik; bu kapalılık/derin hayaldir.",
     ["derin hayal", "kapalı söyleyiş", "ince mazmun", "Naili-Şeyh Galip"]),
    ("Mahallileşme", "divan_uslup",
     "Divan şiirine günlük yaşamdan, halk söyleyişinden ve yerli unsurlardan ögeler katma eğilimi.",
     "Nedim.",
     "Sebk-i Hindi kapalı/derindir; bu yerli/sade/günlüktür.",
     ["yerlilik", "günlük yaşam", "halk söyleyişi", "Nedim"]),
    ("Türkî-i Basit", "divan_uslup",
     "Divan şiirinde Arapça-Farsça tamlamalardan kaçınıp sade Türkçeyle yazma akımı.",
     "Aydınlı Visali, Tatavlalı Mahremi.",
     "Mahallileşme yerli ögelerdir; bu özellikle sade Türkçe/terkipsizliktir.",
     ["sade Türkçe", "terkipsiz", "yabancı tamlamadan kaçınma"]),

    # ============ DİVAN NESİR TÜRLERİ ============
    ("Tezkire", "divan_nesir",
     "Şairlerin hayatlarını, eserlerini ve sanatlarını tanıtan; günümüz biyografi/antoloji karşılığı eser.",
     "Sehî Bey'in Heşt Behişt'i (Anadolu'da ilk örnek).",
     "Menakıbname VELİ kerameti anlatır; bu ŞAİR biyografisidir.",
     ["şair biyografisi", "antoloji", "sanat değerlendirmesi"]),
    ("Münşeat", "divan_nesir",
     "Resmi ve özel mektup ile çeşitli düzyazı örneklerinin bir araya getirildiği derleme.",
     "",
     "Tezkire şair biyografisi; bu MEKTUP/yazı örnekleri derlemesidir.",
     ["mektup derlemesi", "düzyazı örnekleri", "üslup örneği"]),
    ("Fütüvvetname", "divan_nesir",
     "Ahilik/fütüvvet teşkilatının görgü, ahlak ve âdâb kurallarını anlatan öğretici düzyazı.",
     "",
     "Menakıbname keramet, siyasetname devlet yönetimi; bu AHİ/meslek ahlakı kurallarıdır.",
     ["ahi teşkilatı", "meslek ahlakı", "görgü/âdâb", "öğretici"]),
    ("Gazavatname", "divan_nesir",
     "Orduların akınlarını, savaşlarını ve zaferlerini manzum ya da mensur anlatan; tarihe kaynaklık eden eser.",
     "",
     "Sefaretname elçilik, seyahatname gezi; bu SAVAŞ/zafer anlatısıdır.",
     ["savaş/zafer", "ordu akınları", "tarihsel kaynak"]),
    ("Sefaretname", "divan_nesir",
     "Yabancı ülkeye gönderilen elçinin gözlem ve izlenimlerini aktardığı rapor/anı niteliğindeki eser.",
     "Yirmisekiz Mehmed Çelebi'nin Paris Sefaretnamesi.",
     "Seyahatname genel gezi; bu ELÇİLİK görevi raporudur.",
     ["elçi raporu", "yabancı ülke gözlemi", "XVII. yy sonrası"]),
    ("Sûrnâme", "divan_nesir",
     "Şehzadelerin sünnet, doğum ya da evlenme şenliklerini ayrıntılı biçimde anlatan eser.",
     "",
     "Gazavatname savaş; bu DÜĞÜN/şenlik anlatısıdır.",
     ["düğün/şenlik", "saray töreni", "protokol/ayrıntı"]),
    ("Siyasetname", "divan_nesir",
     "Devlet yönetimi, hükümdarlık ve adalet üzerine öğütler veren öğretici eser.",
     "Nizamülmülk'ün Siyasetnamesi.",
     "Pendname genel ahlak öğüdü; bu DEVLET YÖNETİMİ öğütleridir.",
     ["devlet yönetimi", "hükümdara öğüt", "adalet", "öğretici"]),
    ("Pendname (Nasihatname)", "divan_nesir",
     "Ahlak, erdem ve doğru yaşam üzerine genel öğütler içeren öğretici eser.",
     "Güvâhî'nin Pend-nâmesi.",
     "Siyasetname devlet yönetimi; bu GENEL ahlak/erdem öğütleridir.",
     ["genel ahlak öğüdü", "erdem", "didaktik"]),
    ("Kıyafetname", "divan_nesir",
     "İnsanın dış görünüşünden (yüz, beden) karakter ve huy çıkarımı yapan eser; fizyonomi.",
     "",
     "Tezkire biyografi; bu dış görünüş→KARAKTER okumasıdır (fizyonomi).",
     ["fizyonomi", "dış görünüş→huy", "öğretici"]),
    ("Seyahatname", "divan_nesir",
     "Gezilip görülen yerleri; halkları, gelenekleri ve coğrafyayı ayrıntılı gözlemle anlatan eser.",
     "Evliya Çelebi'nin Seyahatnamesi.",
     "Sefaretname elçilik raporu; bu GENEL gezi gözlemidir.",
     ["gezi gözlemi", "mekan/halk tasviri", "coğrafya"]),
    ("Menakıbname (Velayetname)", "divan_nesir",
     "Bir din büyüğünün, velinin olağanüstü hâllerini ve kerametlerini anlatan eser.",
     "Hacı Bektaş Veli Velâyetnâmesi.",
     "Tezkire şair biyografisi; bu VELİ kerameti anlatısıdır.",
     ["veli kerameti", "din büyüğü", "olağanüstü hâller", "menkıbe"]),
    ("Siyer", "divan_nesir",
     "Hz. Muhammed'in hayatını, kişiliğini ve savaşlarını anlatan eser.",
     "",
     "Menakıbname veli kerameti; bu HZ. MUHAMMED'in hayatıdır.",
     ["Hz. Muhammed'in hayatı", "İslam tarihi", "biyografik"]),
    ("Münazara", "divan_nesir",
     "İki kavramın, varlığın ya da kişinin karşılıklı üstünlük tartışmasını konu alan eser.",
     "",
     "Bir tartışma/karşılaştırma metnidir; öğüt veya biyografi değildir.",
     ["karşılıklı tartışma", "üstünlük iddiası", "iki taraf"]),
    ("Lugat (Sözlük)", "divan_nesir",
     "Sözcüklerin anlamlarını veren; iki dil arasında karşılık sunabilen başvuru eseri.",
     "Divânü Lugâti't-Türk, Muhakemetü'l-Lugateyn.",
     "Tezkire biyografi; bu SÖZCÜK/anlam başvuru eseridir.",
     ["sözlük", "kelime anlamı", "başvuru eseri"]),

    # ============ ŞİİR BİLGİSİ — NAZIM BİRİMİ / ÖLÇÜ / KAFİYE ============
    ("Mısra (Dize)", "siir_birim",
     "Şiirin bir satırlık en küçük birimi; tek başına da anlam taşıyabilir.",
     "",
     "Beyit iki dizedir; bu tek satırlık en küçük birimdir.",
     ["tek satır", "en küçük birim", "bağımsız anlam"]),
    ("Beyit", "siir_birim",
     "İki dizeden oluşan; Divan şiirinin temel nazım birimi.",
     "",
     "Dörtlük dört dizedir; bu iki dizeden oluşur.",
     ["iki dize", "Divan birimi", "gazel/kasidede"]),
    ("Dörtlük (Kıta)", "siir_birim",
     "Dört dizeden oluşan; halk şiirinin temel nazım birimi.",
     "",
     "Beyit iki dizedir; bu dört dizeden oluşur.",
     ["dört dize", "halk birimi", "mâni/koşmada"]),
    ("Bent", "siir_birim",
     "İkiden çok dizenin oluşturduğu nazım birimi (beşli, altılı...).",
     "",
     "Beyit/dörtlük sabit sayıdadır; bu çok dizeli gruptur.",
     ["çok dizeli grup", "terkib-i bend/şarkıda", "değişken dize"]),
    ("Hece Ölçüsü", "siir_birim",
     "Dizelerin eş sayıda birimden oluşmasına ve duraklara dayanan; Türklere özgü milli ölçü.",
     "",
     "Aruz, birimlerin uzun-kısalığına; bu ise SAYI eşitliğine dayanır.",
     ["birim sayısı eşitliği", "durak", "milli ölçü", "halk şiiri"]),
    ("Aruz Ölçüsü", "siir_birim",
     "Hecelerin uzunluk-kısalık (açık-kapalı) sırasına dayanan; Arap-Fars kaynaklı ölçü.",
     "",
     "Hece ölçüsü sayıya dayanır; bu hecelerin uzun-kısalığına dayanır.",
     ["açık-kapalı hece", "kalıplar", "Divan şiiri", "Arap-Fars kaynaklı"]),
    ("Serbest Ölçü", "siir_birim",
     "Hece ya da aruz kalıbına bağlı olmayan; ölçü ve uyak zorunluluğu taşımayan söyleyiş.",
     "",
     "Hece/aruz kalıplıdır; bu kalıpsız ve özgürdür.",
     ["ölçü yok", "kalıpsız", "modern şiir", "özgür"]),
    ("Yarım Kafiye", "siir_birim",
     "Tek ses benzerliğine dayanan en zayıf uyak.",
     "",
     "Tam iki, zengin üç+ ses; bu tek ses benzerliğidir.",
     ["tek ses benzerliği", "en zayıf uyak"]),
    ("Tam Kafiye", "siir_birim",
     "İki ses benzerliğine dayanan uyak.",
     "",
     "Yarım tek, zengin üç+ ses; bu iki ses benzerliğidir.",
     ["iki ses benzerliği", "orta uyak"]),
    ("Zengin Kafiye", "siir_birim",
     "İkiden çok ses benzerliğine dayanan uyak.",
     "",
     "Yarım tek, tam iki ses; bu üç ve daha çok ses benzerliğidir.",
     ["üç+ ses benzerliği", "en güçlü uyak"]),
    ("Redif", "siir_birim",
     "Uyaktan sonra gelen; görevi ve anlamı aynı olan, yinelenmiş ek ya da sözcük.",
     "",
     "Kafiye SES benzerliğidir; bu AYNI ek/sözcüğün tekrarıdır.",
     ["uyaktan sonra", "aynı ek/sözcük", "tekrar", "anlamca aynı"]),
    ("Nakarat", "siir_birim",
     "Şarkı, türkü gibi şiirlerde her bendin sonunda yinelenen dize ya da dizeler.",
     "",
     "Redif uyaktan sonraki ektir; bu yinelenen tam dizedir.",
     ["her bent sonunda tekrar", "türkü/şarkı", "yinelenen dize"]),

    # ============ ŞİİR TÜRLERİ ============
    ("Lirik Şiir", "siir_turu",
     "Aşk, özlem, ayrılık gibi bireysel duyguları coşkulu biçimde işleyen şiir türü.",
     "",
     "Epik kahramanlık; bu bireysel duygu/coşkudur.",
     ["duygu yoğun", "bireysel", "coşku", "aşk/özlem"]),
    ("Epik Şiir", "siir_turu",
     "Savaş, kahramanlık ve yiğitlik konularını işleyen; destansı şiir türü.",
     "",
     "Lirik bireysel duygu; bu kahramanlık/destandır.",
     ["kahramanlık", "savaş", "destansı", "yiğitlik"]),
    ("Didaktik Şiir", "siir_turu",
     "Bir bilgi, öğüt ya da ders vermeyi amaçlayan; öğretici şiir türü.",
     "",
     "Lirik duygu; bu öğreti/bilgi amaçlıdır.",
     ["öğretici", "bilgi/öğüt", "ders amaçlı"]),
    ("Pastoral Şiir", "siir_turu",
     "Doğa güzelliklerini, kır ve çoban yaşamını anlatan şiir türü.",
     "",
     "Epik kahramanlık; bu doğa/kır yaşamıdır.",
     ["doğa/kır", "çoban yaşamı", "idil/eglog"]),
    ("Dramatik Şiir", "siir_turu",
     "Acıklı ya da heyecanlı bir olayı; harekete ve sahneye dayalı biçimde işleyen şiir türü.",
     "",
     "Lirik durağan duygu; bu olay/hareket içerir.",
     ["olay/hareket", "trajik/heyecanlı", "sahneye uygun"]),
    ("Satirik Şiir", "siir_turu",
     "Bir kişiyi ya da toplumsal aksaklığı eleştiren, yeren şiir türü.",
     "",
     "Divan'da hicviye, halkta taşlama karşılığıdır.",
     ["eleştiri/yergi", "toplumsal", "alay"]),

    # ============ SÖZ (EDEBÎ) SANATLARI ============
    ("Teşbih (Benzetme)", "soz_sanati",
     "Aralarında ilgi bulunan iki şeyden nitelikçe zayıf olanı güçlü olana benzetme sanatı.",
     "Aslan gibi cesur.",
     "İstiarede tek öge bulunur; bu dört ögeyle (benzeyen-benzetilen) yapılır.",
     ["benzeyen+benzetilen", "benzetme yönü/edatı", "dört öge"]),
    ("İstiare", "soz_sanati",
     "Benzetmenin temel ögelerinden yalnızca biriyle (benzeyen ya da benzetilen) yapılan; kapalı benzetme.",
     "",
     "Teşbihte iki öge vardır; bu tek ögeyle yapılan kapalı benzetmedir.",
     ["tek öge", "kapalı benzetme", "açık/kapalı istiare"]),
    ("Mecaz-ı Mürsel (Ad Aktarması)", "soz_sanati",
     "Bir sözcüğün benzetme amacı gütmeden; parça-bütün, iç-dış, neden-sonuç gibi ilgilerle başka anlamda kullanılması.",
     "Sobayı yaktım (kömürü).",
     "İstiarede benzetme vardır; bunda benzetme YOKTUR.",
     ["benzetmesiz mecaz", "parça-bütün ilgisi", "ad aktarması"]),
    ("Kinaye", "soz_sanati",
     "Bir sözü hem gerçek hem mecaz anlama gelecek biçimde; mecazı kastederek kullanma sanatı.",
     "",
     "Tariz alaylı/tersinedir; bu gerçek+mecaz, mecaz kastedilir.",
     ["gerçek+mecaz", "mecaz kastedilir", "dolaylı"]),
    ("Teşhis (Kişileştirme)", "soz_sanati",
     "İnsan dışı varlıklara insana özgü özellikler verme sanatı.",
     "Ağaçlar el sallıyor.",
     "İntak konuşturur; bu insan özelliği verir.",
     ["insan dışına insan özelliği", "kişileştirme"]),
    ("İntak (Konuşturma)", "soz_sanati",
     "İnsan dışı varlıkları konuşturma sanatı; teşhisle birlikte bulunur.",
     "",
     "Teşhis özellik verir; bu konuşturur.",
     ["konuşturma", "insan dışı varlık", "teşhisle birlikte"]),
    ("Tezat (Karşıtlık)", "soz_sanati",
     "Aralarında karşıtlık bulunan kavramları bir arada kullanma sanatı.",
     "",
     "Tenasüp ilgili/uyumlu sözcüklerdir; bu zıt kavramlardır.",
     ["karşıt kavramlar", "zıtlık"]),
    ("Tenasüp", "soz_sanati",
     "Anlamca birbiriyle ilgili sözcükleri bir arada kullanma sanatı.",
     "",
     "Tezat zıt kavramlardır; bu ilgili/uyumlu sözcüklerdir.",
     ["ilgili sözcükler", "uyum", "bir arada"]),
    ("Telmih", "soz_sanati",
     "Bilinen bir olaya, kişiye ya da inanışa göndermede bulunma sanatı.",
     "Mecnun gibi çöllere düştüm.",
     "Tenasüp uyumdur; bu bilinen olaya göndermedir.",
     ["göndermede bulunma", "bilinen olay/kişi", "hatırlatma"]),
    ("Tariz (İğneleme)", "soz_sanati",
     "Sözü tersine, alaylı bir biçimde kullanarak iğneleme sanatı.",
     "",
     "Kinaye mecaz kasteder; bu tersini söyleyip iğneler.",
     ["tersini söyleme", "alay/iğne", "dolaylı eleştiri"]),
    ("Tevriye", "soz_sanati",
     "İki anlamı olan bir sözcüğü; yakın anlamı sezdirip uzak anlamı kastederek kullanma sanatı.",
     "",
     "Cinas ses benzerliğidir; bu tek sözcüğün iki anlamıdır.",
     ["iki anlamlı sözcük", "uzak anlam kastedilir", "nükte"]),
    ("Cinas", "soz_sanati",
     "Yazılışı/söylenişi aynı, anlamı farklı sözcükleri bir arada kullanma sanatı.",
     "",
     "Tevriye tek sözcüğün iki anlamıdır; bu iki ayrı sözcüktür (ses aynı).",
     ["ses aynı anlam farklı", "sözcük oyunu"]),
    ("Hüsn-i Talil", "soz_sanati",
     "Bir olayı, gerçekte öyle olmadığı hâlde güzel/hayalî bir nedene bağlama sanatı.",
     "",
     "Mübalağa abartır; bu güzel nedene bağlar.",
     ["güzel/hayalî neden", "olayı açıklama", "şairane gerekçe"]),
    ("Mübalağa (Abartma)", "soz_sanati",
     "Bir şeyi olduğundan çok büyük ya da çok küçük gösterme sanatı.",
     "",
     "Hüsn-i talil nedene bağlar; bu abartır.",
     ["abartma", "olduğundan farklı gösterme"]),
    ("Tecahül-i Ârif", "soz_sanati",
     "Bilinen bir şeyi, bir nükte ya da anlam inceliği amacıyla bilmezlikten gelme sanatı.",
     "",
     "Tariz iğnelemedir; bu bilmezden gelmedir.",
     ["bilmezden gelme", "nükte amaçlı", "anlam inceliği"]),

    # ============ DÜZYAZI (NESİR) TÜRLERİ ============
    ("Roman", "nesir_tur",
     "Olmuş ya da olabilecek olayları geniş bir çevrede, ayrıntılı biçimde anlatan uzun kurmaca tür.",
     "",
     "Hikâye kısa ve tek olaylıdır; bu uzun ve çok olaylıdır.",
     ["uzun kurmaca", "çok karakter/olay", "geniş çevre", "ayrıntılı"]),
    ("Olay (Klasik) Hikâyesi", "nesir_tur",
     "Belirgin bir vakanın çatışma ve serim-düğüm-çözüm kurgusuyla, sonuca bağlanarak anlatıldığı öykü türü.",
     "Ömer Seyfettin, Maupassant tarzı.",
     "Durum öyküsünde belirgin vaka/sonuç yoktur; bu vaka/çatışma üzerinedir.",
     ["vaka/çatışma", "serim-düğüm-çözüm", "belirgin sonuç", "Maupassant"]),
    ("Durum (Kesit) Hikâyesi", "nesir_tur",
     "Belirgin bir vakadan çok; günlük yaşamdan bir kesiti, belirgin sonucu olmadan işleyen öykü türü.",
     "Sait Faik, Çehov tarzı.",
     "Olay öyküsünde dramatik vaka/sonuç vardır; bu yaşamdan kesit üzerinedir.",
     ["vaka değil kesit", "yaşamdan kesit", "belirsiz son", "Çehov"]),
    ("Deneme", "nesir_tur",
     "Yazarın bir konuda kesin yargılara varmadan, kanıtlama kaygısı gütmeden samimi düşüncelerini 'ben'li bir dille anlattığı tür.",
     "Montaigne, Nurullah Ataç.",
     "Makale nesnel ve kanıtlıdır; bu öznel ve serbesttir.",
     ["öznel", "kanıt kaygısız", "samimi/ben'li", "serbest düşünce"]),
    ("Makale", "nesir_tur",
     "Bir düşünceyi ya da bilgiyi kanıtlara dayanarak savunan; nesnel ve öğretici tür.",
     "",
     "Deneme özneldir; bu nesnel ve kanıtlıdır.",
     ["nesnel", "kanıtlı", "öğretici", "savunma"]),
    ("Fıkra (Gazete)", "nesir_tur",
     "Güncel bir konuyu, yazarın kişisel görüşüyle ve kanıtlama kaygısı gütmeden kısaca işlediği gazete yazısı.",
     "",
     "Makale kanıtlar; halk fıkrası sözlü/güldürüdür. Bu güncel + kişisel görüştür.",
     ["güncel konu", "kişisel görüş", "kısa", "gazete yazısı"]),
    ("Sohbet (Söyleşi)", "nesir_tur",
     "Yazarın bir konuyu, okuyucuyla konuşuyormuş gibi samimi bir dille işlediği tür.",
     "",
     "Deneme 'ben' merkezlidir; bu okuyucuyla 'konuşma' havasındadır.",
     ["konuşma havası", "samimi", "okuyucuya seslenme"]),
    ("Eleştiri (Tenkit)", "nesir_tur",
     "Bir eseri ya da sanatçıyı çeşitli yönlerden inceleyip değerlendiren; iyi-kötü yönlerini ortaya koyan tür.",
     "",
     "Makale genel düşünce savunur; bu bir eseri değerlendirir.",
     ["eser değerlendirme", "inceleme", "iyi-kötü yön"]),
    ("Anı (Hatıra)", "nesir_tur",
     "Yazarın yaşadığı ya da şahit olduğu olayları, aradan zaman geçtikten sonra anlattığı tür.",
     "",
     "Günlük o gün yazılır; bu olaylar sonradan kaleme alınır.",
     ["geçmiş olaylar", "sonradan yazma", "şahitlik"]),
    ("Günlük", "nesir_tur",
     "Yazarın gün gün yaşadıklarını ve izlenimlerini, tarih atarak o gün yazdığı tür.",
     "",
     "Anı sonradan yazılır; bu o gün ve tarihlidir.",
     ["tarihli", "o gün yazılır", "kişisel izlenim"]),
    ("Biyografi", "nesir_tur",
     "Bir kişinin hayatını, başkası tarafından nesnel biçimde anlatan tür.",
     "",
     "Otobiyografide kişi kendi hayatını anlatır; bunda başkası anlatır.",
     ["başkasının hayatı", "nesnel", "yaşam öyküsü"]),
    ("Otobiyografi", "nesir_tur",
     "Bir kişinin kendi hayatını kendisinin anlattığı tür.",
     "",
     "Biyografide başkası anlatır; bunda kişi kendisini anlatır.",
     ["kendi hayatı", "birinci ağız", "öz yaşam öyküsü"]),
    ("Röportaj", "nesir_tur",
     "Bir yer, kişi ya da olayın; gözlem, görüşme ve araştırmayla ayrıntılı tanıtıldığı gazetecilik türü.",
     "",
     "Anı kişiseldir; bu gözlem+görüşme+araştırmaya dayanır.",
     ["gözlem+görüşme", "araştırma", "gazetecilik"]),

    # ============ TANZİMAT KAVRAMLARI ============
    ("Toplum İçin Sanat", "tanzimat_kavram",
     "Sanatın; halkı eğitmek ve aydınlatmak için bir araç sayıldığı anlayış (Tanzimat I. dönem).",
     "",
     "'Sanat şahsî ve muhteremdir' bireysel/özgürdür; bu, sanatı halka araç sayar.",
     ["sanat araçtır", "halkı eğitme", "toplumsal fayda", "Tanzimat I"]),
    ("Alafrangalık (Yanlış Batılılaşma)", "tanzimat_kavram",
     "Batı'yı yalnızca dış görünüş ve gösterişte taklit eden; züppe tipiyle eleştirilen yanlış yönelim.",
     "Bihruz Bey, Felatun Bey.",
     "Gerçek Batılılaşma öz/değer alır; bu yüzeysel taklit/gösteriştir.",
     ["yüzeysel Batı taklidi", "züppe tipi", "eleştirilir", "gösteriş"]),

    # ============ SERVET-İ FÜNUN / FECR-İ ÂTİ KAVRAMLARI ============
    ("Mensur Şiir", "sf_kavram",
     "Ölçü ve uyak bulunmayan; ama şiirsel bir dil, ahenk ve duygu yoğunluğu taşıyan düzyazı.",
     "Halit Ziya, Mehmet Rauf.",
     "Serbest nazım dizelidir; bu düzyazı biçiminde ama şiirseldir.",
     ["ölçüsüz-uyaksız", "şiirsel dil", "ahenk", "düzyazı biçimi"]),
    ("Sanat Şahsî ve Muhteremdir", "sf_kavram",
     "Estetiğin bireysel, özgür ve her türlü toplumsal kısıtlamadan uzak olması gerektiğini savunan ilke (Fecr-i Âti).",
     "",
     "'Toplum için sanat'ın karşıtıdır; bu, estetiği bireysel/özgür sayar.",
     ["bireysel sanat", "özgürlük", "Fecr-i Âti ilkesi"]),
    ("Sone", "sf_kavram",
     "İki dörtlük ve iki üçlükten oluşan; Batı kaynaklı, Servet-i Fünun'da kullanılan nazım biçimi.",
     "",
     "Türk biçimleri farklıdır; bu Batı kaynaklı 14 dizeli biçimdir.",
     ["iki dörtlük + iki üçlük", "Batı kaynaklı", "on dört dize"]),

    # ============ MİLLİ EDEBİYAT KAVRAMLARI ============
    ("Yeni Lisan", "milli_kavram",
     "Dilde sadeleşmeyi; konuşma diliyle yazı dilini birleştirmeyi savunan hareket (Genç Kalemler).",
     "Ömer Seyfettin, Ziya Gökalp.",
     "Servet-i Fünun ağır dillidir; bu sade dili savunur.",
     ["dil sadeleşmesi", "konuşma=yazı dili", "Genç Kalemler"]),
    ("Memleket Edebiyatı", "milli_kavram",
     "Anadolu'yu, halkı ve yurdun gerçeklerini konu edinen edebiyat anlayışı.",
     "",
     "Servet-i Fünun bireysel/İstanbul odaklıdır; bu Anadolu/halk odaklıdır.",
     ["Anadolu/halk", "yurt gerçekleri", "milli tema"]),
    ("Milli Vezin (Hece)", "milli_kavram",
     "Aruz yerine; Türklere özgü hece ölçüsünün benimsenmesi.",
     "",
     "Aruz Arap-Fars kaynaklıdır; bu milli/hece ölçüsüdür.",
     ["hece ölçüsü", "aruz reddi", "milli ölçü"]),

    # ============ CUMHURİYET ŞİİR TOPLULUKLARI ============
    ("Yedi Meşaleciler", "cumhuriyet_topluluk",
     "1928'de canlılık-içtenlik-yenilik ve 'sanat sanat içindir' ilkesiyle çıkan; en kalıcı ismi Ziya Osman Saba olan topluluk.",
     "",
     "Garip gündelik/yalındır; bu yenilik iddialı ama klasik kalmış bir topluluktur.",
     ["1928", "yenilik iddiası", "sanat için sanat", "Ziya Osman Saba"]),
    ("Garip (Birinci Yeni)", "cumhuriyet_topluluk",
     "Ölçü, uyak ve şairaneliği reddedip; gündelik dili ve sıradan insanı şiire sokan akım (Orhan Veli öncülüğünde).",
     "Orhan Veli, Oktay Rifat, Melih Cevdet.",
     "İkinci Yeni kapalı/imgelidir; bu yalın/açık ve gündeliktir.",
     ["ölçü-uyak reddi", "gündelik dil", "sıradan insan", "Orhan Veli"]),
    ("İkinci Yeni", "cumhuriyet_topluluk",
     "Garip'in yalınlığına tepki olarak; kapalı, imgeli, soyut ve bireysel bir şiir kuran akım.",
     "Cemal Süreya, Turgut Uyar, Edip Cansever.",
     "Garip yalın/açıktır; bu kapalı/imgeli ve soyuttur.",
     ["kapalı/imgeli", "soyut", "bireysel", "Cemal Süreya"]),
    ("Hisarcılar", "cumhuriyet_topluluk",
     "Garip ve İkinci Yeni'ye karşı; geleneğe, milli değerlere ve anlaşılır şiire bağlı kalan topluluk.",
     "Mehmet Çınarlı, İlhan Geçer.",
     "Garip/İkinci Yeni yenilikçidir; bu gelenekçi ve anlaşılırdır.",
     ["gelenekçi", "milli değer", "anlaşılır şiir", "Hisar dergisi"]),
    ("Maviciler", "cumhuriyet_topluluk",
     "Garip'e tepki gösteren; daha derin, sanatlı ve zengin bir şiiri savunan topluluk (Attila İlhan öncülüğünde).",
     "Attila İlhan.",
     "Garip yalındır; bu derin/sanatlı şiiri savunur.",
     ["Garip karşıtı", "sanatlı/derin şiir", "Mavi dergisi", "Attila İlhan"]),
    ("Toplumcu Gerçekçiler", "cumhuriyet_topluluk",
     "Toplumsal sorunları, emekçiyi ve sınıf çatışmasını Marksist bir bakışla işleyen anlayış.",
     "Nazım Hikmet.",
     "Saf şiir ideolojiden uzaktır; bu toplumsal/ideolojiktir.",
     ["toplumsal sorun", "emekçi/sınıf", "Marksist bakış", "Nazım Hikmet"]),
    ("Saf (Öz) Şiir", "cumhuriyet_topluluk",
     "Şiiri her türlü ideolojiden arındırıp; biçim kusursuzluğu, müzik ve imgeyi öne çıkaran anlayış.",
     "Ahmet Haşim, Yahya Kemal.",
     "Toplumcu gerçekçilik ideolojiktir; bu ideolojiden uzak/biçimcidir.",
     ["ideolojiden uzak", "biçim kusursuzluğu", "müzik/imge", "Ahmet Haşim"]),

    # ============ ROMAN / ANLATIM KAVRAMLARI ============
    ("Serbest Nazım", "cumhuriyet_kavram",
     "Ölçü ve uyak zorunluluğu olmadan; dizelerin özgürce düzenlendiği şiir biçimi.",
     "Nazım Hikmet.",
     "Mensur şiir düzyazı biçimindedir; bu dizeli ama ölçüsüzdür.",
     ["ölçüsüz-uyaksız", "özgür dize", "Nazım Hikmet"]),
    ("Bilinç Akışı", "cumhuriyet_kavram",
     "Roman kişisinin zihninden geçenlerin; mantık sırası gözetilmeden, çağrışımlarla ve aracısız aktarıldığı anlatım tekniği.",
     "",
     "İç monolog düzenli ve yazar denetimlidir; bu düzensiz/aracısızdır.",
     ["düzensiz çağrışım", "aracısız zihin", "mantık dışı sıra"]),
    ("İç Monolog", "cumhuriyet_kavram",
     "Roman kişisinin iç sesinin; düzenli biçimde ve yazarın denetiminde aktarıldığı teknik.",
     "",
     "Bilinç akışı düzensiz/aracısızdır; bu düzenli ve kontrollüdür.",
     ["iç ses", "düzenli", "yazar denetimli"]),
    ("Postmodern Roman", "cumhuriyet_kavram",
     "Kurmaca olduğunu açıkça hissettiren; üst-kurmaca, metinlerarasılık ve oyunbazlıkla örülü roman anlayışı.",
     "Orhan Pamuk, Oğuz Atay.",
     "Klasik roman gerçeklik yanılsaması kurar; bu kurmacayı açıkça gösterir.",
     ["üst-kurmaca", "metinlerarasılık", "kurmaca farkındalığı", "oyunbazlık"]),

    # ============ BATI EDEBİYATI AKIMLARI ============
    ("Klasisizm", "akim",
     "Akıl, kurallar ve eski Yunan-Latin örneklerine bağlılığı; soylu konuları ve genel insan tipini öne çıkaran akım.",
     "Molière, Racine, La Fontaine.",
     "Romantizm duygu/bireydir; bu akıl/kural ve genel tiptir.",
     ["akıl/kural", "antik örnek", "genel insan tipi", "Molière"]),
    ("Romantizm", "akim",
     "Klasisizme tepki olarak; duyguyu, hayali ve bireyi öne çıkaran, doğaya yönelen akım.",
     "Victor Hugo, Lamartine.",
     "Klasisizm akıldır; bu duygu/hayal ve bireydir.",
     ["duygu/hayal", "birey", "doğa", "Victor Hugo"]),
    ("Realizm", "akim",
     "Gözlem ve gerçeğe bağlılıkla; toplumu ve insanı olduğu gibi, abartısız anlatan akım.",
     "Stendhal, Balzac, Flaubert.",
     "Romantizm hayaldir; bu gözlem/gerçek ve abartısızdır.",
     ["gözlem", "gerçeğe bağlılık", "abartısız", "Balzac"]),
    ("Natüralizm", "akim",
     "Realizmi ileri götürüp; insanı kalıtım ve çevrenin ürünü sayan, bilimsel/deneysel bakışlı akım.",
     "Émile Zola.",
     "Realizm gözlemdir; bu + kalıtım/çevre ve deneydir.",
     ["kalıtım+çevre", "deneysel/bilimsel", "Zola"]),
    ("Parnasizm", "akim",
     "Şiirde 'sanat sanat içindir' ilkesiyle; biçim kusursuzluğunu ve nesnelliği öne çıkaran akım.",
     "",
     "Sembolizm sezgi/müziktir; bu biçim kusursuzluğu ve nesnelliktir.",
     ["biçim kusursuzluğu", "nesnellik", "sanat için sanat", "şiir"]),
    ("Sembolizm", "akim",
     "Anlamı açıkça söylemeyip; sembol, müzik ve sezgiyle dolaylı duygu uyandırmayı amaçlayan akım.",
     "Baudelaire, Verlaine, Mallarmé.",
     "Parnasizm nesnel/biçimcidir; bu sembol/sezgi ve kapalıdır.",
     ["sembol/imge", "müzik", "sezgi", "kapalılık"]),
    ("Empresyonizm (İzlenimcilik)", "akim",
     "Varlıkların kendisini değil; sanatçıda bıraktığı anlık izlenimi yansıtan akım.",
     "",
     "Ekspresyonizm iç dünyayı dışa vurur; bu dış varlığın anlık izlenimidir.",
     ["anlık izlenim", "öznel algı", "dış gerçek değil izlenim"]),
    ("Ekspresyonizm (Dışavurumculuk)", "akim",
     "Sanatçının iç dünyasını ve ruhsal çalkantılarını; abartılı, çarpıtılmış biçimde dışa vuran akım.",
     "",
     "Empresyonizm dış izlenimdir; bu iç dünyanın çarpıtılmış dışavurumudur.",
     ["iç dünya", "çarpıtma/abartı", "ruhsal dışavurum"]),
    ("Fütürizm (Gelecekçilik)", "akim",
     "Geçmişi reddedip; hız, makine, teknoloji ve dinamizmi yücelten akım.",
     "Marinetti, Mayakovski.",
     "Dadaizm anlamsızlık/başkaldırıdır; bu hız/makine yüceltimidir.",
     ["hız/makine", "geçmiş reddi", "dinamizm"]),
    ("Dadaizm", "akim",
     "Her türlü kural, anlam ve geleneği reddeden; başkaldırı ve anlamsızlığı öne çıkaran akım.",
     "Tristan Tzara.",
     "Sürrealizm bilinçaltı/rüyadır; bu kural/anlam reddi ve başkaldırıdır.",
     ["kural/anlam reddi", "başkaldırı", "anlamsızlık"]),
    ("Sürrealizm (Gerçeküstücülük)", "akim",
     "Bilinçaltını, rüyaları ve otomatik yazıyı temel alan; Freud etkili akım.",
     "André Breton.",
     "Dadaizm yıkıcılıktır; bu bilinçaltı/rüya temellidir.",
     ["bilinçaltı", "rüya", "otomatik yazı", "Freud etkisi"]),
    ("Egzistansiyalizm (Varoluşçuluk)", "akim",
     "İnsanın özgürlüğünü, seçimlerini ve varoluşunu öne çıkaran felsefi-edebî akım.",
     "Sartre, Camus.",
     "Diğer akımlar biçim/duygu odaklıdır; bu varoluş/özgürlük felsefesidir.",
     ["varoluş", "özgürlük/seçim", "bireysel sorumluluk", "Sartre-Camus"]),
]


def slugify(s):
    s = unicodedata.normalize('NFD', str(s))
    s = ''.join(c for c in s if not unicodedata.combining(c))
    s = s.lower().replace('ı', 'i').replace('ş', 's').replace('ç', 'c').replace('ğ', 'g').replace('ö', 'o').replace('ü', 'u')
    return re.sub(r'^-|-$', '', re.sub(r'[^a-z0-9]+', '-', s))


def main():
    # Spoiler kontrolü: tanım, terim adını (veya ana kökünü) içermemeli
    spoiler = []
    kaynak = []
    for terim, kat, tanim, ornek, ayirt, ozellikler in TERIMLER:
        if kat not in KATEGORI:
            print(f"⚠ Bilinmeyen kategori: {kat} ({terim})")
            continue
        kat_label, konu, donem_label, _ = KATEGORI[kat]
        # spoiler: terimin ilk kelimesinin kökü tanımda geçiyor mu (>=4 harf; kısa kökler false-positive)
        ana = slugify(terim.split('(')[0].split(' ')[0])
        if ana and len(ana) >= 4 and ana in slugify(tanim):
            spoiler.append(terim)
        kaynak.append({
            'terim': terim,
            'slug': slugify(terim),
            'kategori': kat,
            'kategori_label': kat_label,
            'konu': konu,
            'donem': donem_label,
            'tanim': tanim,
            'ornek': ornek,
            'ayirt_edici': ayirt,
            'ozellikler': ozellikler,
        })

    OUT_KAYNAK.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_KAYNAK, 'w', encoding='utf-8') as f:
        json.dump({'_meta': {'toplam': len(kaynak), 'kategori_sayisi': len(set(t['kategori'] for t in kaynak))},
                   'terimler': kaynak}, f, ensure_ascii=False, indent=2)

    # Sayfa görüntü yapısı: dönem → kategori → terimler
    from collections import OrderedDict
    by_donem = OrderedDict()
    for t in kaynak:
        by_donem.setdefault(t['donem'], OrderedDict())
        by_donem[t['donem']].setdefault((t['kategori'], t['kategori_label']), [])
        by_donem[t['donem']][(t['kategori'], t['kategori_label'])].append({
            'terim': t['terim'], 'tanim': t['tanim'], 'ornek': t['ornek'], 'ayirt_edici': t['ayirt_edici'],
        })
    page = {'donemler': []}
    for donem in sorted(by_donem, key=lambda d: DONEM_SIRA.get(d, 99)):
        kats = []
        for (kat, kat_label), terimler in by_donem[donem].items():
            kats.append({'kategori': kat, 'kategori_label': kat_label, 'terimler': terimler})
        page['donemler'].append({'donem': donem, 'kategoriler': kats})
    with open(OUT_PAGE, 'w', encoding='utf-8') as f:
        json.dump(page, f, ensure_ascii=False, indent=2)

    print(f"✓ terimler_kaynak.json: {len(kaynak)} terim, {len(set(t['kategori'] for t in kaynak))} kategori")
    print(f"✓ terimler.json (sayfa): {len(page['donemler'])} dönem")
    if spoiler:
        print(f"⚠ SPOILER riski (tanım terim adını içeriyor): {spoiler}")
    else:
        print("✓ Spoiler kontrolü temiz (tanımlar terim adını içermiyor)")


if __name__ == '__main__':
    main()
